<a href="https://colab.research.google.com/github/pranith7867/Deep-Learning/blob/main/Pytorch_tutorial_1%5BTensors%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import torch
import numpy as np

### Intializing a Tensor

**Directly from data**

In [6]:
data  = [[1,2],[3,4]]
x_data = torch.tensor(data) #Converting to tensor
print(x_data.dtype)
print(x_data)

torch.int64
tensor([[1, 2],
        [3, 4]])


**From a numpy array**


In [7]:
np_array = np.array(data) #Converting Data into numpy array
x_np = torch.from_numpy(np_array) #Converting Data into Tensor from numpy array
print(x_np.dtype)
print(np_array.dtype)

torch.int64
int64


**From another Tensor**

In [8]:
x_ones = torch.ones_like(x_data) #gets propeties from from x_data
print(x_ones)

tensor([[1, 1],
        [1, 1]])


In [18]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
x_rand

tensor([[0.9528, 0.7283],
        [0.7899, 0.7359]])

**With Random or Constant values**

In [19]:
x_rand = torch.rand(x_data.shape)
x_rand

tensor([[0.6488, 0.9241],
        [0.5163, 0.7686]])

In [20]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9431, 0.8340, 0.1777],
        [0.1103, 0.2169, 0.7151]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**Attributes of A Tensor**

In [21]:
print(x_data.shape) # Shape attribute
print(x_data.device) # device attribute
print(x_data.dtype) # datatype attribute

torch.Size([2, 2])
cpu
torch.int64


### Operations on Tensors

In [24]:
# We Move Tensors to Gpu for better tiem and memory
if torch.cuda.is_available():
  print("YEAH YOU HAVE A GPU ")
  tensor = tensor.to('cuda')
else:
  print("BETTER LUCK NEXT TIME FOR GPU")

BETTER LUCK NEXT TIME FOR GPU


**Standard numpy-like indexing and slicing**

In [27]:
tensor = torch.rand(4,4)
print("First row: ", tensor[0])
print("First Column: ", tensor[:, 0])
print("Last Column: ", tensor[:, -1])
tensor[:, 1] = 0 #updating First Column
print("Tensor: ", tensor)

First row:  tensor([0.1685, 0.6270, 0.5616, 0.5479])
First Column:  tensor([0.1685, 0.7224, 0.4310, 0.9545])
Last Column:  tensor([0.5479, 0.5405, 0.4582, 0.2762])
Tensor:  tensor([[0.1685, 0.0000, 0.5616, 0.5479],
        [0.7224, 0.0000, 0.8493, 0.5405],
        [0.4310, 0.0000, 0.6063, 0.4582],
        [0.9545, 0.0000, 0.3894, 0.2762]])


**Joining tensors**

In [34]:
tensor = torch.cat([tensor,tensor,tensor], dim=1)
tensor

tensor([[0.1685, 0.0000, 0.5616,  ..., 0.0000, 0.5616, 0.5479],
        [0.7224, 0.0000, 0.8493,  ..., 0.0000, 0.8493, 0.5405],
        [0.4310, 0.0000, 0.6063,  ..., 0.0000, 0.6063, 0.4582],
        ...,
        [0.7224, 0.0000, 0.8493,  ..., 0.0000, 0.8493, 0.5405],
        [0.4310, 0.0000, 0.6063,  ..., 0.0000, 0.6063, 0.4582],
        [0.9545, 0.0000, 0.3894,  ..., 0.0000, 0.3894, 0.2762]])

**Arithmetic operations**

In [38]:
tensor = torch.ones(3,3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = y3)


tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [41]:
y1

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [42]:
y2

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [43]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Single-Element Tensors**

In [44]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [47]:
agg = tensor.sum() #Returns the sum of a Tensor
agg_item = agg.item()
agg_item

9.0

**In-Place opeartions**


```
Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x
```



In [48]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


### Bridge With Numpy

**Tensors to numpy array**

In [50]:
t = torch.ones(5,5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
n: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


A change in the tensor reflects in the NumPy array.

In [51]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
n: [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


**Numpy array to Tensor**

In [52]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [53]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
